---
ttn:
  mqtt_url: "tcp://eu1.cloud.thethings.network:1883"
  identity_server_url: "https://eu1.cloud.thethings.network"
  identity_server_timeout: 30
  apps:
  - name: "sensorcommunity-mkr1310"
    key: "7F4PO63TKAF7I24UP6HHR33GKHWOA5NKW25ZZNA"
decoder:
  encoding: "TEXT"
  separator: " "
  properties:
  - index: 0
    item: "TEMP"
  - index: 1
    item: "HUMI"
  - index: 2
    item: "PM10"
  - index: 3
    item: "PM2_5"
nbiot:
  port: 9000
senscom:
  url: "https://api.sensor.community"
  timeout: 30
opensense:
  url: "https://api.opensensemap.org"
  timeout: 30
geolocation:
  url: "https://location.services.mozilla.com"
  timeout: 30
  apikey: "test"

